name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v3
    - name: Set up conda ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        activate-environment: tomotwin
        channel-priority: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge, pytorch, nvidia, rapidsai, defaults
        environment-file: conda_env.yml
    - run: conda --version
    - run: conda init bash
    - run: |
        which python
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint tox tox-gh-actions pytest pytest-coverage
        pip install .
    - name: Debug Info
      run: |
        which python
        pip freeze
    - name: Analysing the code with pylint
      run: |
        pylint -E $(git ls-files '*.py')
    - name: Tests
      run: |
        pytest -v --cov=./ --cov-report=xml
      env:
        PLATFORM: ${{ matrix.platform }}
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
